'Restriction on elytra boosts by fireworks':
  'Enabled or not': true
  'Messaging intervals': 300
  #The unit are in seconds.
  'Applied or not regardless of TPS': false
  'Target worlds':
    - world
    - world_nether
    - world_the_end
    - shigen
    - shigen2
  #If you add "- ALL", all worlds will be included.
  'TPS Threshold to which the restriction applies': 16
  'Message':
    'When the plugin started appling the restriction': "TPS減少のため、エリトラブースター制限を実施します！"
    'When the plugin stopped appling the restriction': "TPSが復活しましたのでエリトラブースター制限を解除します。ご協力ありがとうございました！"
    'When the plugin blocked elytra boosting': "只今エリトラブースター制限が実施されています。ご不便お掛けしますがご協力お願いします。"
'Temporary boat':
  'Enabled or not': true
  'Target worlds':
    - world
    - world_nether
    - world_the_end
    - shigen
    - shigen2
  #If you add "- ALL", all worlds will be included.
'Regeneration of regions':
  'Origin world': "origin"
  'Maximum number of blocks that can be regenerated': 100000
'Kicking AFKer':
  'Enabled or not': true
  'AFKed time required for kicks': 5
  #The unit are in minutes.
  'Message to send when the plugin kick AFKer': "放置状態で一定時間が経過したためキックされました。"