name: MamiyaAssist
main: amata1219.mamiya.assist.MamiyaAssist
version: 2.0.0
api-version: "1.16"
softdepend: [Essentials]
author: "@amata1219"

commands:
  mamiya:
    permission: mamiya.assist.command.mamiya
    permission-message: "You don't have <permission>"