name: MamiyaAssist
main: amata1219.mamiya.assist.MamiyaAssist
version: 1.7.1
api-version: 1.13
softdepend: [WorldEdit, Essentials]
author: amata1219(Twitter@amata1219)

commands:
  mamiya:
    description: mamiya command.
    usage: /<command> commands
    permission: mamiya.assist.command.mamiya
    permission-message: You do not have permission "<permission>".